# Generated by Django 4.2.3 on 2023-07-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0004_business_created_at_business_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
