# Generated by Django 4.2.3 on 2023-09-25 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0007_remove_business_owner_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
