# Generated by Django 4.2.3 on 2023-09-26 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0008_owner_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="business_id",
            new_name="business",
        ),
    ]
