# Generated by Django 4.2.3 on 2023-09-27 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0010_alter_owner_business"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="owner",
            new_name="user",
        ),
    ]
