# Generated by Django 4.2.3 on 2023-07-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("01", "CASH"),
                            ("02", "CREDIT"),
                            ("03", "CASH/CREDIT"),
                            ("04", "BANK CHECK"),
                            ("05", "DEBIT AND CREDIT CARD"),
                            ("06", "MOBILE MONEY"),
                            ("07", "OTHER"),
                        ],
                        max_length=3,
                    ),
                ),
                ("properties", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_created", models.DateTimeField(auto_now=True)),
                ("time_paid", models.DateTimeField(null=True)),
                (
                    "sale_amount_with_tax",
                    models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
                ),
                ("tax_amount", models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ("receipt_type", models.CharField(choices=[("S", "Sale"), ("C", "Credit Note")], max_length=2)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("01", "Wait for Approval"),
                            ("02", "Approved"),
                            ("03", "Credit Note Requested"),
                            ("04", "Cancelled"),
                            ("05", "Credit Note Generated"),
                            ("06", "Transferred"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "sale_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "Wait for Approval"),
                            ("02", "Approved"),
                            ("03", "Credit Note Requested"),
                            ("04", "Cancelled"),
                            ("05", "Credit Note Generated"),
                            ("06", "Transferred"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "business_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sale", to="administration.business"
                    ),
                ),
                (
                    "cashier_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sales", to="administration.employee"
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="administration.customer",
                    ),
                ),
                (
                    "payment_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sale", to="sales.paymentmode"
                    ),
                ),
            ],
        ),
    ]
