# Generated by Django 4.2.3 on 2023-07-11 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_alter_sales_options_remove_sales_time_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsales",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productsales",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sales",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sales",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
