# Generated by Django 4.2.3 on 2023-07-13 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_productsales_created_at_productsales_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_pin", models.CharField(blank=True, max_length=255, null=True)),
                ("email_address", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="paymentmode",
            name="properties",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sales",
            name="customer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="sales.customer",
            ),
        ),
    ]
