# Generated by Django 4.2.3 on 2023-07-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_customer_alter_paymentmode_properties_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TransactionType",
        ),
        migrations.AlterModelOptions(
            name="paymentmode",
            options={"verbose_name": "Payment Modes"},
        ),
        migrations.AlterField(
            model_name="sales",
            name="transaction_type",
            field=models.CharField(
                choices=[("C", "Copy"), ("N", "Normal"), ("P", "Proforma"), ("T", "Training")], max_length=2
            ),
        ),
    ]
