# Generated by Django 4.2.3 on 2023-07-13 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_alter_sales_options_remove_sales_time_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="paymentmode",
            options={"verbose_name": "Payment Mode"},
        ),
        migrations.RemoveField(
            model_name="paymentmode",
            name="mode",
        ),
        migrations.AlterField(
            model_name="sales",
            name="payment_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="sales.paymentmode",
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="sale_amount_with_tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="paymentmode",
            name="payment_method",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="sales.paymentmethod"
            ),
        ),
    ]
