# Generated by Django 4.2.3 on 2023-07-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_paymentmethod_alter_paymentmode_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmode",
            name="payment_method",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sales.paymentmethod"),
        ),
    ]
