# Generated by Django 4.2.3 on 2023-07-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0008_alter_paymentmode_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsales",
            old_name="products",
            new_name="product_id",
        ),
        migrations.RenameField(
            model_name="productsales",
            old_name="sales",
            new_name="sale_id",
        ),
        migrations.AlterField(
            model_name="paymentmode",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("01", "CASH"),
                    ("02", "CREDIT"),
                    ("03", "CASH/CREDIT"),
                    ("04", "BANK CHECK"),
                    ("05", "DEBIT AND CREDIT CARD"),
                    ("06", "MOBILE MONEY"),
                    ("07", "OTHER"),
                ],
                default="01",
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
