# Generated by Django 4.2.3 on 2023-07-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0006_delete_customer"),
        ("sales", "0010_remove_productsales_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="business_id",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale",
                to="administration.business",
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="cashier_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="administration.employee",
            ),
        ),
    ]
