# Generated by Django 4.2.3 on 2023-07-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_stock_stock_movement_quantity"),
        ("sales", "0011_alter_sales_business_id_alter_sales_cashier_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsales",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="product_sales", to="products.product"
            ),
        ),
        migrations.AlterField(
            model_name="productsales",
            name="sale_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="product_sales", to="sales.sales"
            ),
        ),
    ]
