# Generated by Django 4.2.3 on 2023-07-14 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0012_alter_productsales_product_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsales",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="productsales",
            old_name="sale_id",
            new_name="sale",
        ),
    ]
