# Generated by Django 4.2.3 on 2023-11-06 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0012_alter_owner_business"),
        ("sales", "0018_purchaseproduct_delete_purchasestock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="supplier_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="administration.supplier",
            ),
        ),
    ]
