# Generated by Django 4.2.3 on 2023-11-06 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0019_alter_purchase_supplier_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="supplier_id",
            new_name="supplier",
        ),
        migrations.RenameField(
            model_name="purchase",
            old_name="user_id",
            new_name="user",
        ),
    ]
