# Generated by Django 4.2.3 on 2023-11-06 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0020_rename_supplier_id_purchase_supplier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase",
            old_name="user",
            new_name="employee",
        ),
    ]
