# Generated by Django 4.2.3 on 2023-11-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0012_alter_owner_business"),
        ("sales", "0021_rename_user_purchase_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sales",
            old_name="customer_id",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="sales",
            old_name="cashier_id",
            new_name="employee",
        ),
        migrations.RenameField(
            model_name="sales",
            old_name="payment_id",
            new_name="payment",
        ),
        migrations.RenameField(
            model_name="sales",
            old_name="business_id",
            new_name="business",
        ),
    ]
