# Generated by Django 4.2.3 on 2023-11-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0012_alter_owner_business"),
        ("sales", "0022_rename_customer_id_sales_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="business",
            field=models.ForeignKey(
                blank=True,
                default=42,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale",
                to="administration.business",
            ),
        ),
    ]
