# Generated by Django 4.2.3 on 2023-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0023_alter_sales_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="receipt_label",
            field=models.CharField(default="NS", max_length=5),
        ),
        migrations.AlterField(
            model_name="sales",
            name="receipt_type",
            field=models.CharField(choices=[("S", "Sale"), ("C", "Credit Note")], default="S", max_length=2),
        ),
        migrations.AlterField(
            model_name="sales",
            name="sale_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Wait for Approval"),
                    ("02", "Approved"),
                    ("03", "Credit N ote Requested"),
                    ("04", "Cancelled"),
                    ("05", "Credit Note Generated"),
                    ("06", "Transferred"),
                ],
                default="01",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sales",
            name="transaction_type",
            field=models.CharField(
                choices=[("C", "Copy"), ("N", "Normal"), ("P", "Proforma"), ("T", "Training")],
                default="N",
                max_length=2,
            ),
        ),
    ]
