# Generated by Django 4.2.3 on 2023-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0024_alter_sales_receipt_label_alter_sales_receipt_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsales",
            name="tax_rate",
            field=models.CharField(default="B", max_length=5),
        ),
    ]
