# Generated by Django 4.2.3 on 2023-11-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0025_alter_productsales_tax_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="sale_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Wait for Approval"),
                    ("02", "Approved"),
                    ("03", "Credit Note Requested"),
                    ("04", "Cancelled"),
                    ("05", "Credit Note Generated"),
                    ("06", "Transferred"),
                ],
                default="01",
                max_length=3,
                null=True,
            ),
        ),
    ]
