# Generated by Django 4.2.3 on 2023-11-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0026_alter_sales_sale_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                default="01",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="sales.paymentmode",
            ),
        ),
    ]
