# Generated by Django 4.2.3 on 2023-11-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0027_alter_sales_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
