# Generated by Django 4.2.3 on 2023-11-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0028_sales_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="change",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
