# Generated by Django 4.2.3 on 2023-11-15 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0029_sales_change"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="supplier",
        ),
    ]
