# Generated by Django 4.2.3 on 2023-11-16 00:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0012_alter_owner_business"),
        ("sales", "0030_remove_purchase_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseproduct",
            name="supplier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_products",
                to="administration.supplier",
            ),
            preserve_default=False,
        ),
    ]
