# Generated by Django 4.2.3 on 2023-11-22 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0032_alter_sales_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="sales.customer",
            ),
        ),
    ]
