# Generated by Django 4.2.3 on 2023-12-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0033_alter_sales_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsales",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sales",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
