# Generated by Django 4.2.3 on 2023-12-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0034_productsales_discount_sales_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
