# Generated by Django 4.2.3 on 2023-07-08 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="uploads/")),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="uploads/")),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("slug", models.SlugField()),
                ("code", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("1", "Raw Material"), ("2", "Finished Product"), ("3", "Service Without Stock")],
                        max_length=2,
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("A", "A-Exempt"),
                            ("B_16", "B-16%"),
                            ("C", "C-0%"),
                            ("D", "D-Non-VAT"),
                            ("E", "E-8%"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("PR", "Pair"),
                            ("AV", "Cap"),
                            ("BA", "Barrel"),
                            ("BE", "bundle"),
                            ("BG", "bag"),
                            ("BL", "block"),
                            ("BLL", "BLL Barrel (petroleum) (158,987 dm3)"),
                            ("BX", "box"),
                            ("CA", "Can"),
                            ("CEL", "Cell"),
                            ("CMT", "centimetre"),
                            ("CR", "CARAT"),
                            ("DR", "Drum"),
                            ("DZ", "Dozen"),
                            ("GLL", "Gallon"),
                            ("GRM", "GRAM"),
                            ("GRO", "Gross"),
                            ("KG", "Kilogram"),
                            ("KTM", "kilometre"),
                            ("KWT", "kilowatt"),
                            ("LTR", "Litre"),
                            ("LBR", "pound"),
                            ("LK", "link"),
                            ("MTR", "Metre"),
                            ("M2", "Square Metre"),
                            ("M3", "Cubic Metre"),
                            ("MGM", "milligram"),
                            ("MWT", "megawatt hour (1000 Kw.h)"),
                            ("NO", "Number"),
                            ("NX", "part per thousand"),
                            ("PA", "packet"),
                            ("PG", "plate"),
                            ("RL", "reel"),
                            ("RO", "roll"),
                            ("SET", "set"),
                            ("ST", "sheet"),
                            ("TNE", "tonne (metric ton)"),
                            ("TU", "tube"),
                            ("U", "Pieces/item[Number]"),
                            ("YRD", "yard"),
                        ],
                        max_length=5,
                    ),
                ),
                ("limited", models.BooleanField(null=True)),
                ("active_for_sale", models.BooleanField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="products.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "product_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                ("stock_quantity", models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("cost_per_unit", models.DecimalField(decimal_places=2, max_digits=6)),
                ("price_per_unit_retail", models.DecimalField(decimal_places=2, max_digits=6)),
                ("price_per_unit_wholesale", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reorder_level", models.IntegerField(null=True)),
                ("reorder_quantity", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
                (
                    "supplier",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="administration.supplier"),
                ),
            ],
        ),
    ]
