# Generated by Django 4.2.3 on 2023-07-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_category_created_at_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_movement_quantity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
