# Generated by Django 4.2.3 on 2023-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_stock_stock_movement_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tax_type",
            field=models.CharField(
                choices=[("A", "A-Exempt"), ("B", "B-16%"), ("C", "C-0%"), ("D", "D-Non-VAT"), ("E", "E-8%")],
                max_length=5,
            ),
        ),
    ]
