# Generated by Django 4.2.3 on 2023-10-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_tax_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="lead_time",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
