# Generated by Django 4.2.3 on 2023-11-12 22:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_supplierproduct_lead_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="product_id",
            new_name="product",
        ),
    ]
