# Generated by Django 4.2.3 on 2023-11-17 04:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_rename_product_id_stock_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
