# Generated by Django 4.2.3 on 2023-11-18 01:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_supplierproduct_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="stock_movement_quantity",
            new_name="latest_stock_movement_quantity",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="stock_movement_remarks",
            new_name="latest_stock_movement_remarks",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="stock_movement_type",
            new_name="latest_stock_movement_type",
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("01", "Incoming-Import"),
                            ("02", "Incoming-Purchase"),
                            ("03", "Incoming-Return"),
                            ("04", "Incoming-Stock Movement"),
                            ("05", "Incoming-Processing"),
                            ("06", "Incoming-Adjustment"),
                            ("11", "Outgoing-Sale"),
                            ("12", "Outgoing-Return"),
                            ("13", "Outgoing-Stock Movement"),
                            ("14", "Outgoing-Processing"),
                            ("15", "outgoing-Discarding"),
                            ("16", "outgoing-Adjustment"),
                        ],
                        max_length=4,
                    ),
                ),
                ("movement_quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("remarks", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="movement", to="products.stock"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
