# Generated by Django 4.2.3 on 2023-11-20 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_rename_stock_movement_quantity_stock_latest_stock_movement_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
