# Generated by Django 4.2.3 on 2023-11-21 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0012_alter_owner_business"),
        ("products", "0010_stockmovement_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stockmovement",
                to="administration.employee",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="previous_stock_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="The stock quantity before the stock movement",
                max_digits=10,
            ),
        ),
    ]
