# Generated by Django 4.2.3 on 2023-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_stockmovement_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="cost_per_unit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="stock",
            name="price_per_unit_retail",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="stock",
            name="price_per_unit_wholesale",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="stock",
            name="reorder_level",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="reorder_quantity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
