# Generated by Django 4.2.3 on 2024-01-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_stock_cost_per_unit_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(fields=["product", "supplier"], name="products_su_product_7fb1d1_idx"),
        ),
    ]
